# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# actually we can combine ci and cd together but in this case i create respectfly

name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CD
        run : echo 'CD ongoing'
      - name: Ssh 
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.VPS_HOUSE_IP }}
         username: ${{ secrets.VPS_HOUSE_USERNAME }}
         key: ${{ secrets.RMW_PRIVATE }}
         port: 22
         script: |
           /var/apps/exame-service
           npm i
           npm run