# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# actually we can combine ci and cd together but in this case i create respectfly

name: CI CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : checkoute
        uses: actions/checkout@v3
      - name: use Nodejs 16
        uses: actions/setup-node@v1
        with:
            node-version: 16
      - run: npm i
      - name: CD
        run : echo 'CD on going'
      - name: Ssh 
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.VPS_HOUSE_IP }}
         username: ${{ secrets.VPS_HOUSE_USERNAME }}
         key: ${{ secrets.RMW_PRIVATE }} # so this is privatekey of local computer, and add public key to server
         port: 22
         script: |
           cd /var/apps/exame-service
           git pull origin main
           export NVM_DIR=~/.nvm # because node installed using nvm , and nvm didn install node in /usr/local/bin/
           source ~/.nvm/nvm.sh
           echo "DATABASE_URL=\"${{secrets.DATABASE_URL_PROD}}\"" > .env
           echo "PORT=3000" >> .env
           npm install
           npx prisma migrate dev
